# Generated by Django 4.0 on 2025-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_contabilidad', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('procesador', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=50)),
                ('capacidad_max', models.CharField(max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('velocidad', models.CharField(blank=True, max_length=50, null=True)),
                ('disco_duro', models.CharField(max_length=50)),
                ('capacidad', models.CharField(max_length=50)),
                ('version_windows', models.CharField(max_length=50)),
                ('clave_windows', models.CharField(blank=True, max_length=50, null=True)),
                ('version_office', models.CharField(max_length=50)),
                ('clave_office', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('any_desk', models.CharField(blank=True, max_length=50, null=True)),
                ('clave_admin', models.CharField(blank=True, max_length=50, null=True)),
                ('funcionario_a_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('funcionario_registra', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
